spring:
  application:
    name: EmailSender-POC
  mail:
    host: ${MAIL_SENDER_HOST:smtp-mail.outlook.com}
    port: ${MAIL_SENDER_PORT:587}
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SENDER_AUTH:true}
          starttls:
            enable: ${MAIL_SENDER_STARTTLS_ENABLE:true}